version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: commitments
      POSTGRES_PASSWORD: commitments
      POSTGRES_DB: commitments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Commitments.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=db;Username=commitments;Password=commitments;Database=commitments
    ports:
      - "8080:8080"
    depends_on:
      - db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025" # web ui
      - "1025:1025" # smtp
volumes:
  pgdata:
  minio:
